### ISSUE TITLE
improve README/docs

### ISSUE THREAD

**Issue by travis-g** [travis-g/bang#5]
- Add more details about the config file,
- More detailed usage info/`fs.Usage()`

**Comment by smhmd** [comment]
![image](https://user-images.githubusercontent.com/46059092/74103789-59d74080-4b4f-11ea-8518-fecd7181443c.png)

> Add more details about the config file,

Yes, please.

**Comment by travis-g** [comment]
Hi! To resolve that panic, `bang` currently searches for the following, in order ([code](https://github.com/travis-g/bang/blob/b231da5961d2a8d1133ba806edce10077764485d/main.go#L25-L27)):
- ~~`~/.config/bangs/bangs.[json|yaml|toml|hcl]`~~ (Edit: as of f9de40c8230fe1e68231a185a0fe8a61315ebdd8, `~/.config/bang/bangs.[json|yaml|toml|hcl]`
- `${PWD}/bangs.[json|yaml|toml|hcl]`

The fatal error is a [Viper](https://github.com/spf13/viper) error getting surfaced, but I'll add some friendlier messaging and error handling around that since it's pretty unclear. I don't think it'd hurt to have the CLI look for the config file directly in `~/.config/` as well, so I'll add that to the config file search paths (Edit: done as of f9de40c8230fe1e68231a185a0fe8a61315ebdd8)
