### ISSUE TITLE
[Feature Request] Read from stdin

### ISSUE THREAD

**Issue by smhmd** [travis-g/bang#7]
**Problem**
I'm trying to make a [`dmenu`](https://tools.suckless.org/dmenu/) script (I can make a script out of the current implementation, but not comfy one-liners).

Being able to type the bang with the search is better than going through two menus, IMO.

**Proposal**
```sh
$ echo b search term | bang - # translates to bang b search term
```

**Comment by travis-g** [comment]
Totally doable, basically if [`fs.Arg(0)`](https://github.com/travis-g/bang/blob/f9de40c8230fe1e68231a185a0fe8a61315ebdd8/main.go#L81) is a hyphen, it'd use `os.Stdin` in place of `fs.Args()`. I should be able to add this within the day or so. Thanks for the suggestion!
